### ISSUE TITLE
Meer functionele suggestie

### ISSUE THREAD

**Issue by JordyMoos** [hielkedevries/bob-the-builder-memory#1]
Hey man lekker bezig!
Ziet er heel goed uit!

https://github.com/hielkedevries/bob-the-builder-memory/blob/a32049bed6d9db7ed1f6656dc7d84b74cc01807b/src/Memory.elm#L108

Kleine suggestie voor een meer functionele aanpak.
Hoewel ik jou oplossing wel heel creatief vind!
Dit kan ongeveer zo ;)
```elm
imageRecords1
        |> List.filter (\item -> item.id == id) -- Filter/Zoek naar het juiste item
        |> List.map .url -- Map de lijst van juiste items naar alleen hun url
        |> List.head -- Probeer de eerste van de lijst terug te geven. Dit geeft een Option
        |> Maybe.withDefault "" -- Unpack de Option/Maybe met een default waarde
```

**Comment by frevib** [comment]
Aah, thanks! Goed punt.
